version: '3'

services:
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    networks:
      - citrolux_network
    ports:
      - "1337:1337"
    volumes:
      - ./uploads:/app/public/uploads
      - ./tmp:/app/.tmp

  next_app:
    build:
      context: ./site
      dockerfile: Dockerfile
    networks:
      - citrolux_network
    ports:
      - "3030:3030"
    restart: always


networks:
  citrolux_network:
    driver: bridge
